---
type: spine
spine:
  defaults:
    campus: MandE
    platform: "{{ platform_clab_type | default('7280SR3') }}"
    spanning_tree_mode: mstp
    spanning_tree_priority: 16384
    loopback_ipv4_pool: 10.101.30.0/24
    vtep_loopback_ipv4_pool: 10.101.40.0/24
    uplink_ipv4_pool: 10.101.50.0/24
    virtual_router_mac_address: 00:1c:73:00:dc:11
    
    bgp_defaults:
      - "no bgp default ipv4-unicast"
      - "graceful-restart restart-time 300"
      - "graceful-restart"

  node_groups:
    - group: BLUE_SPINES
      bgp_as: 65100
      filter:
        tenants: [all]
        tags:
          - "spines"
          - "blue"
          - "blue_site1"
          - "site1"
      nodes:
        - name: SW101-SITE1-B
          id: 1
          campus_pod: SITE1
          campus_access_pod: Blue
          # inband_mgmt_subnet: 10.12.12.0/24
          # inband_mgmt_interface: Vlan112
          ## inband_mgmt_vrf: Production
          ## inband_mgmt_ip: 10.0.10.11/24
          # inband_mgmt_vlan: 1112

          mgmt_ip: "{{ ansible_host }}/{{ mgmt_cidr | default('24') }}"
          # mgmt_interface: Management0
          structured_config:
            loopback_interfaces:
              - name: "Loopback10"
                ip_address: 10.0.10.11/32
                description: INBAND_MGMT
                vrf: Production
            router_bgp:
              neighbors:
                  - ip_address: 10.11.30.4
                    peer_group: EVPN-OVERLAY-PEERS
                    remote_as: 65203
                    description: SW203-SITE2-P                  
                  - ip_address: 10.11.30.5
                    peer_group: EVPN-OVERLAY-PEERS
                    remote_as: 65301
                    description: SW301-SITE3-P
                  - ip_address: 10.101.30.5
                    peer_group: EVPN-OVERLAY-PEERS
                    remote_as: 65501
                    description: SW501-SITE5-B
# Multicast Vlans
            vlans:
              - id: 130
                name: JXSVideoTrafficBLUE
            vlan_interfaces:
              - name: Vlan130
                description: JXSVideoTrafficBLUE
                ip_address: 10.1.30.1/24 
                pim:
                  ipv4:
                    sparse_mode: true
                isis_enable: EVPN_UNDERLAY
            underlay_multicast: true
            router_pim_sparse_mode:
              ipv4:
                rp_addresses:
                  - address: 10.101.30.1
                    groups:
                      - 236.1.0.0/18
            ip_igmp_snooping:
              globally_enabled: true
              vlans:
                - id: 130
                  enabled: true
                - id: 112
                  enabled: true
                  querier:
                    enabled: true
                    address: 10.101.30.1
                - id: 113
                  enabled: true
                  querier:
                    enabled: true
                    address: 10.101.30.1
            router_multicast:
              ipv4:
                routing: true
                software_forwarding: kernel
            static_routes:
              #   # VRF Name.
              - vrf: Production
                # IPv4_network/Mask.
                destination_address_prefix: 0.0.0.0/0
                gateway: 10.1.99.1
                name: "Default_prod_iTransit_MX"
