---
# Fabric name
# fabric_name: EASTCOAST_FABRIC

evpn_l3_multicast: true
# evpn_multicast: true
underlay_multicast: true
igmp_snooping_enabled : true
default_igmp_snooping_enabled: true
# topology_hint_datacenter: MandE
# Set Design Type to l3ls-evpn
design:
  type: l3ls-evpn

underlay_routing_protocol: isis
overlay_routing_protocol: ebgp

digital_twin:

  # Targeted Digital Twin environment.
  environment: act
  fabric:
    act_username: cvpadmin2
    act_password: blabla


# # BGP peer groups passwords
# bgp_peer_groups:
#   # all passwords set to "arista"
#   evpn_overlay_peers:
#     password: Q4fqtbqcZ7oQuKfuWtNGRQ==
#   ipv4_underlay_peers:
#     password: 7x4B4rnJhZB438m9+BrBfQ==
#   mlag_ipv4_underlay_peer:
#     password: 4b21pAdCvWeAqpcKDFMdWw==

# node_type_keys:
custom_node_type_keys:

  - key: spine
    type: spine
    default_evpn_role: server
    default_ptp_priority1: 20
    cv_tags_topology_type: spine
    connected_endpoints: true
    vtep: true
    network_services:
        l1: true
        l2: true
        l3: true
    default_overlay_address_families:
      - evpn
    default_evpn_encapsulation: vxlan
    underlay_router: true
  # - key: l3leaf
  #   type: l3leaf
  #   connected_endpoints: true
  #   default_evpn_role: client
  #   mlag_support: true
  #   network_services:
  #     l2: true
  #     l3: true
  #   vtep: true
  #   default_ptp_priority1: 30
  #   cv_tags_topology_type: leaf
# Platform Settings
# platform_settings:
#   - platforms: ['default']
#     reload_delay:
#       mlag: 300
#       non_mlag: 330
#   - platforms: ['720XP-48', '720XP-96']
#     reload_delay:
#       mlag: 300
#       non_mlag: 330
#     trident_forwarding_table_partition: "flexible exact-match 16000 l2-shared 24000 l3-shared 24000"
#   - platforms: ['7050TX3-48', '7050SX3-48']
#     reload_delay:
#       mlag: 300
#       non_mlag: 330
#     trident_forwarding_table_partition: "flexible exact-match 16384 l2-shared 98304 l3-shared 131072"

eos_designs_documentation:
  topology_csv: true
  p2p_links_csv: true

### Management console ###
management_console:
  idle_timeout: 300

management_ssh:
  idle_timeout: 60
  connection:
    limit: 5


### DNS Domain ###
dns_domain: tech-eh.ca

# Common settings
load_interval:
  default: 30

clock:
  timezone: Canada/Eastern

# ### NTP Servers ###
# ntp:
#   servers:
#     - name: 216.232.132.95
#       vrf: MGMT
#     - name: 23.133.168.244
#       vrf: MGMT
    # - name: 216.232.132.95
    #   vrf: Production
    # - name: 23.133.168.244
    #   vrf: Production



ipv6_unicast_routing: false

shutdown_interfaces_towards_undeployed_peers: false

interface_defaults:
  ethernet:
    shutdown: true
#   # mtu: 8000

errdisable:
  recovery:
    causes:
      - bpduguard
      - link-flap
    interval: 30

local_users:
  - name: ansible
    privilege: 15
    role: network-admin
    # Password set to "ansible". Same string as the device generates when configuring a username.
    sha512_password: $6$7u4j1rkb3VELgcZE$EJt2Qff8kd/TapRoci0XaIZsL4tFzgq1YZBLD9c6f/knXzvcYY0NcMKndZeCv0T268knGKhOEwZAxqKjlMm920
  - name: admin
    privilege: 15
    role: network-admin
    no_password: true
  - name: cvpadmin
    privilege: 15
    role: network-admin
    # Password set to "ansible". Same string as the device generates when configuring a username.
    sha512_password: $6$hNPJ7EFOvJgas3zQ$.HncN6qfuBQsZW/reDwSkVi0h9SHarJTmOkotMT7XK7/N958w5zd7IhvGRkY7ekUcrKs6kJRr/85PVIdKSWpH.
    ssh_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJF7OT/UyUNugQBV/6sn/7FPB5glZfb2KzjBmlkxyWdx westley.dion@Westleys-MacBook-Pro-2.local"
  - name: service
    sha512_password: $6$xqN6kvscOiKvO4K0$uMr17y1EGzBOu0e3k7UrTbx5.dHqluAQ0KB5i.Qck6Md5lc0iAx7TGPlXORqzGxZLg.ro6ggy0C/CNdBIH52j.
    shell: /bin/bash
  - name: pcapper
    shell: /bin/bash
    sha512_password: $6$hNPJ7EFOvJgas3zQ$.HncN6qfuBQsZW/reDwSkVi0h9SHarJTmOkotMT7XK7/N958w5zd7IhvGRkY7ekUcrKs6kJRr/85PVIdKSWpH.
    ssh_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJF7OT/UyUNugQBV/6sn/7FPB5glZfb2KzjBmlkxyWdx westley.dion@Westleys-MacBook-Pro-2.local"

  - name: evanr
    privilege: 15
    role: network-admin
    # Password set to "ansible". Same string as the device generates when configuring a username.
    sha512_password: $6$hNPJ7EFOvJgas3zQ$.HncN6qfuBQsZW/reDwSkVi0h9SHarJTmOkotMT7XK7/N958w5zd7IhvGRkY7ekUcrKs6kJRr/85PVIdKSWpH.
    ssh_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBpGd3WjhAdwNn9t4dbbDbwHdnLFrjaj6Xw+MW7AI9En azuread\evanrolfe@LAPTOP-389PFP4E"


# P2P interfaces MTU, includes VLANs 4093 and 4094 that are over peer-link
# If you're running vEOS-lab or cEOS, you should use MTU of 1500 instead as shown in the following line
# p2p_uplinks_mtu: 8000
p2p_uplinks_mtu: 1500


# # DNS Server
# ip_name_servers:
#   - ip_address: 8.8.8.8
#     vrf: MGMT
#   - ip_address: 4.2.2.1
#     vrf: MGMT

#   - ip_address: 8.8.8.8
#     vrf: Production
#   - ip_address: 4.2.2.1
#     vrf: Production

# generate_cv_tags:
#   topology_hints: true
#   campus_fabric: true
#   device_tags:
#     - name: mc_colour
#       value: blue

# AAA settings
# aaa_server_groups:
#   - name: PAT-Server
#     type: "tacacs+"
#     servers:
#       - server: 10.210.207.11
#       - server: 10.219.207.11
#   - name: LAB-CPPM
#     type: "radius"
#     servers:
#       - server: 10.104.196.125


# aaa_accounting:
#   exec:
#     default:
#       type: "start-stop"
#       group: PAT-Server
#   system:
#     default:
#       type: "start-stop"
#       group: PAT-Server
#   dot1x:
#     default:
#       type: "start-stop"
#       group: LAB-CPPM
#   commands:
#     default:
#       - commands: "15"
#         type: "start-stop"
#         group: PAT-Server

# aaa_authentication:
#   login:
#     default: local group PAT-Server
#   enable:
#     default: local group PAT-Server
#   dot1x:
#     default: group LAB-CPPM

# aaa_authorization:
#   serial_console: true
#   config_commands: true
#   exec:
#     default: local group PAT-Server
#   commands:
#     all_default: local group PAT-Server
#     privilege:
#       - level: 15

aaa_authorization:
  serial_console: true
  config_commands: true
  exec:
    default: local 
  commands:
    all_default: local
    privilege:
      - level: 15

radius_server:
  hosts:
    - host: radsec.beta.agni.arista.io
      tls:
        enabled: true
        ssl_profile: agni-server

aaa_server_groups:
  - name: agni-server-group
    type: radius
    servers:
      - server: radsec.beta.agni.arista.io tls

aaa_accounting:
#   exec:
#     default:
#       type: "start-stop"
#       group: PAT-Server
#   system:
#     default:
#       type: "start-stop"
#       group: PAT-Server
  dot1x:
    default:
      type: "start-stop"
      group: agni-server-group
#   commands:
#     default:
#       - commands: "15"
#         type: "start-stop"
#         group: PAT-Server


aaa_authentication:
  # login:
  #   default: local group PAT-Server
  # enable:
  #   default: local group PAT-Server
  dot1x:
    default: group agni-server-group

dot1x:
  dynamic_authorization: true
  system_auth_control: true
  protocol_lldp_bypass: true

# tacacs_servers:
#   hosts:
#     - host: 10.210.207.11
#       key: "111A1C0605171F"
#     - host: 10.219.207.11
#       key: "13161211190910"

# DHCP
ip_dhcp_snooping:
  enabled: true
  information_option:
    enabled: false

# QOS
# qos:
#   rewrite_dscp: false

# dot1x
# dot1x:
#   aaa:
#     unresponsive:
#       phone_action:
#         traffic_allow: true
#       action:
#         traffic_allow_vlan: 5
#   radius_av_pair:
#     service_type: true
#   system_auth_control: true
#   protocol_lldp_bypass: true
#   dynamic_authorization: true



# sflow
# sflow:
#   sample: 300
#   polling_interval: 5
#   destinations:
#     - destination: 127.0.0.1
#   source_interface: Vlan196
#   run: true


# banners
banners:
  login: |
    ***********************************************
    Go away!
    EOF

#alias
aliases: |
  alias cc clear counters
  alias cp clear platform trident counters
  alias senz show interface counter error | nz
  alias shmc show int | awk '/^[A-Z]/ { intf = ck216 } /, address is/ { print intf, }'
  alias snz show interface counter | nz
  alias sqnz show interface counter queue | nz
  alias srnz show interface counter rate | nz
  alias ps_show_bess bash ps -ef | grep -i Bess


# SNMP
# snmp_server:
#   engine_ids:
#     local: f5717fac3d940dbe0100
#   contact: NOC 416-490-5888 or 888-982-5557 - 7x24
#   location: SOC LAB 2nd floor
#   communities:
#     - name: MandE-RO
#       access: ro
#       access_list_ipv4:
#         name: '66'
#     - name: MandE-RW
#       access: rw
#       access_list_ipv4:
#         name: '66'
#   local_interfaces:
#     - name: Vlan196
#       # vrf: default
#   ipv4_acls:
#     - name: '66'
#       # vrf: default
#   views:
#     - name: NAC-VIEW
#       mib_family_name: iso
#       included: true
#     - name: SNMPv3View
#       mib_family_name: iso
#       included: true
#   groups:
#     - name: SNMPv3Group
#       version: v3
#       authentication: priv
#       read: SNMPv3View
#     - name: SNMPv3Group-CP
#       version: v3
#       authentication: priv
#       read: SNMPv3View
#     - name: MandEnetworkt00ls
#       version: v3
#       authentication: priv

#   users:
#     - name: MandEnetworkt00ls
#       group: SNMPv3Group
#       version: v3
#       localized: f5717fac3d940dbe0100
#       auth: sha
#       auth_passphrase: 2f57XXXXXXXX
#       priv: aes
#       priv_passphrase: 2f57bXXXXXXXXX
#   hosts:
#     - host: 10.104.197.182
#       version: 3
#       users:
#         - username: MandEnetworkt00ls
#           authentication_level: priv
#     - host: 10.109.191.12
#       version: 3
#       users:
#         - username: MandEnetworkt00ls
#           authentication_level: priv
#     - host: 49.32.69.56
#       version: 2c
#       community: MandE
#     - host: 49.32.69.97
#       version: 2c
#       community: MandE
#   traps:
#     snmp_traps:
#       - name: entity
#         enabled: true
#       - name: capacity arista-hardware-utilization-alert
#         enabled: true
#       - name: external-alarm
#         enabled: true
#       - name: ospf if-state-change
#         enabled: true
#       - name: ospf nbr-state-change
#         enabled: true
#       - name: snmp link-down
#         enabled: true
#       - name: snmp link-up
#         enabled: true
#       - name: switchover
#         enabled: true

# # Logging
# logging:
#   vrfs:
#     - name: default
#       hosts:
#         - name: 10.49.192.13
#         - name: 10.49.64.17

vrfs:
  - name: MGMT
    description: Management
    ip_routing: true

management_api_http:
  enable_http: false
  enable_https: true
  enable_vrfs:
    - name: MGMT


# MGMT Interface
mgmt_interface_vrf: MGMT

static_routes:

  - vrf: Production
    # IPv4_network/Mask.
    destination_address_prefix: 0.0.0.0/0
    gateway: 10.1.99.1
    name: "Default_prod_iTransit_MX"    
# Handling AVD schema not available yet
# eos_cli: |-
  

#   system l1
#     unsupported speed action warn
#     unsupported error-correction action warn
#   event-handler BessMgr_rebooter
#    trigger on-boot
#    action bash FastCli -p 15 -c "bash rm -f /mnt/flash/kernel-params && agent BessMgr terminate"
#    delay 20

#   action bash FastCli -p 15 -c "bash rm /mnt/flash/kernel-params"

#   boot console speed 115200
#   dot1x
#      eapol unresponsive action traffic allow vlan 5
#      vlan assignment group phone members 10
#   !
#   snmp-server group MandE-NAC-GROUP v3 auth context vlan
#   !
#   management ssh
#      login timeout 60
#   !
