---

# Definition of connected endpoints in the fabric.

generic_devices:

##############################################
# Switchport config for SW501-SITE5-B

# # WAN FROM SITE5 - BELL
#   - name: WAN SITE5 BELL
#     adapters:
#       - switch_ports:
#           - Ethernet1
#           - Ethernet2
#         switches: 
#           - SW501-SITE5-B
#           - SW501-SITE5-B
#         descriptions: 
#           - Bell Internet WAN IN - 15
#           - BU
#         profile: WAN_SITE5_BELL

##############################################
# Switchport config for SW502-SITE5-R


# # WAN FROM SITE5 - ROGERS
#   - name: WAN SITE5 ROGERS
#     adapters:
#       - switch_ports:
#           - Ethernet1
#           - Ethernet2
#         switches: 
#           - SW502-SITE5-R
#           - SW502-SITE5-R
#         descriptions: 
#           - ROGERS Internet WAN IN
#           - BU
#         profile: WAN_SITE5_ROGERS

