---

# Definition of connected endpoints in the fabric.

generic_devices:

##############################################
# Switchport config for SW201-SITE2-B

##############################################
# Switchport config for SW201-SITE2-B

##############################################
# Switchport config for SW203-SITE2-P

