---

# Definition of connected endpoints in the fabric.

generic_devices:

##############################################
# Switchport config for SW201-SITE2-B

# JXSVideoTraffic
  - name: JXSVideoTrafficBlue
    # Definition of adapters on the server.
    adapters:
      - switch_ports:
          - Ethernet1
          - Ethernet2
          - Ethernet3
        switches: 
          - SW201-SITE2-B
          - SW201-SITE2-B
          - SW201-SITE2-B
        descriptions: 
          - Appear JPEG XS Kit 1 Sw 1 D1
          - Appear JPEG XS Kit 1 Sw 1 D2
          - Appear JPEG XS Kit 1 Sw 1 D2 Backup
        profile: JXSVideoTrafficBlue_site2

##############################################
# Switchport config for SW201-SITE2-B

# JXSVideoTraffic
  - name: JXSVideoTrafficRed
    # Definition of adapters on the server.
    adapters:
      - switch_ports:
          - Ethernet1
          - Ethernet2
          - Ethernet3
        switches: 
          - SW202-SITE2-R
          - SW202-SITE2-R
          - SW202-SITE2-R
        descriptions: 
          - Appear JPEG XS Kit 1 Sw 2 D1
          - Appear JPEG XS Kit 1 Sw 2 D2
          - Appear JPEG XS Kit 1 Sw 2 D2 Backup
        profile: JXSVideoTrafficRed_site2


##############################################
# Switchport config for SW203-SITE2-P

# Intercom
  - name: Intercom
    adapters:
      - switch_ports:
          - Ethernet1
          - Ethernet2
          - Ethernet3
        switches: 
          - SW203-SITE2-P
          - SW203-SITE2-P
          - SW203-SITE2-P
        descriptions: 
          - RVON intercom
          - SFP Populated for BU
          - SFP Populated for BU
        profile: Intercom_site2

# DataTransferEVS
  - name: DataTransferEVS
    adapters:
      - switch_ports:
          - Ethernet4
          - Ethernet5
          - Ethernet6
          - Ethernet51
        switches: 
          - SW203-SITE2-P
          - SW203-SITE2-P
          - SW203-SITE2-P
          - SW203-SITE2-P
        descriptions: 
          - SFP Populated for BU
          - EVS X File - Data Transfer - NIC4
          - SFP Populated for BU
          - EVS Fiber
        profile: DataTransferEVS_site2          

# HaivisionSRTTrafficBlue
  - name: HaivisionSRTTrafficBluePurple
    adapters:
      - switch_ports:
          - Ethernet9
          - Ethernet15
          - Ethernet17
          - Ethernet19
          - Ethernet21
          - Ethernet23
          - Ethernet25
          - Ethernet27
          - Ethernet29
          - Ethernet31
          - Ethernet33
          - Ethernet35
        switches: 
          - SW203-SITE2-P
          - SW203-SITE2-P
          - SW203-SITE2-P
          - SW203-SITE2-P
          - SW203-SITE2-P
          - SW203-SITE2-P
          - SW203-SITE2-P
          - SW203-SITE2-P
          - SW203-SITE2-P
          - SW203-SITE2-P
          - SW203-SITE2-P
          - SW203-SITE2-P
        descriptions:
          - SRT Kiloview
          - Haivision Encoder 201 NIC1
          - Haivision Encoder 202 NIC1
          - Haivision Encoder 203 NIC1
          - Haivision Encoder 204 NIC1
          - Haivision Encoder 205 NIC1
          - Haivision Encoder 206 NIC1
          - Haivision Decoder 21 NIC1
          - Haivision DEcoder 22 NIC1
          - Haivision Standby
          - Haivision Standby
          - Haivision Standby
        profile: HaivisionSRTTrafficBlue_site2    

# HaivisionSRTTrafficRed
  - name: HaivisionSRTTrafficRedPurple
    adapters:
      - switch_ports:
          - Ethernet16
          - Ethernet18
          - Ethernet20
          - Ethernet22
          - Ethernet24
          - Ethernet26
          - Ethernet28
          - Ethernet30
          - Ethernet32
          - Ethernet34
          - Ethernet36
        switches: 
          - SW203-SITE2-P
          - SW203-SITE2-P
          - SW203-SITE2-P
          - SW203-SITE2-P
          - SW203-SITE2-P
          - SW203-SITE2-P
          - SW203-SITE2-P
          - SW203-SITE2-P
          - SW203-SITE2-P
          - SW203-SITE2-P
          - SW203-SITE2-P
        descriptions:
          - Haivision Encoder 201 NIC2
          - Haivision Encoder 202 NIC2
          - Haivision Encoder 203 NIC2
          - Haivision Encoder 204 NIC2
          - Haivision Encoder 205 NIC2
          - Haivision Encoder 206 NIC2
          - Haivision Decoder 21 NIC2
          - Haivision DEcoder 22 NIC2
          - Haivision Standby
          - Haivision Standby
          - Haivision Standby
        profile: HaivisionSRTTrafficRed_site2    

# Prod Police
  - name: ProdiNet500mbps
    adapters:
      - switch_ports:
          - Ethernet37
          - Ethernet28
          - Ethernet39
          - Ethernet40
        switches: 
          - SW103-SITE1-P
          - SW103-SITE1-P
          - SW103-SITE1-P
          - SW103-SITE1-P
        descriptions:
          - Prod iNet 500Mbps - Drop 1
          - Prod iNet 500Mbps - Drop 2
          - Prod iNet 500Mbps - Drop 3
          - Prod iNet 500Mbps - Drop 4
        profile: Prod_Police_500mbps

# EdgeDeviceControl
  - name: EdgeDeviceControl
    adapters:
      - switch_ports:
          - Ethernet41
          - Ethernet42
          - Ethernet43
          - Ethernet44
        switches: 
          - SW203-SITE2-P
          - SW203-SITE2-P
          - SW203-SITE2-P
          - SW203-SITE2-P
        descriptions:
          - Operations PC	
          - Appear Control 1	SW 1 CRTL
          - Appear Control 2	SW 2 CRTL
          - Standby	
        profile: EdgeDeviceControl_site2    

# SITE5akiPurple
  - name: SITE5akiPurple
    adapters:
      - switch_ports:
          - Ethernet45
          - Ethernet46
          - Ethernet49
          - Ethernet50
          - Ethernet52
        switches: 
          - SW203-SITE2-P
          - SW203-SITE2-P
          - SW203-SITE2-P
          - SW203-SITE2-P
          - SW203-SITE2-P
        descriptions:
          - SITE5aki Sw 21
          - SITE5aki Sw 22
          - SITE5aki Sw 21 Standby
          - SITE5aki Sw 22 Standby
          - SITE5aki Sw 23
        profile: SITE5AKI_MX_TRUNK
        enabled: true


