---

# Definition of connected endpoints in the fabric.

##############################################
# Switchport config for SW301-SITE3-P

generic_devices:
# Intercom
  - name: Intercom
    adapters:
      - switch_ports:
          - Ethernet1
          - Ethernet2
          - Ethernet3
        switches: 
          - SW301-SITE3-P
          - SW301-SITE3-P
          - SW301-SITE3-P
        descriptions: 
          - RVON intercom 
          - SFP Populated for BU
          - SFP Populated for BU
        profile: Intercom_site3

# EdgeDeviceControl
  - name: EdgeDeviceControl
    adapters:
      - switch_ports:
          - Ethernet21
          - Ethernet22
          - Ethernet23
          - Ethernet24
        switches: 
          - SW301-SITE3-P
          - SW301-SITE3-P
          - SW301-SITE3-P
          - SW301-SITE3-P
        descriptions:
          - Operations PC
          - Standby
          - Standby
          - Standby
        profile: EdgeDeviceControl_site3    

# HaivisionSRTTrafficBlue
  - name: HaivisionSRTTrafficBluePurple
    adapters:
      - switch_ports:
          - Ethernet11
          - Ethernet13
          - Ethernet15
          - Ethernet17
        switches: 
          - SW301-SITE3-P
          - SW301-SITE3-P
          - SW301-SITE3-P
          - SW301-SITE3-P
        descriptions:
          - Haivision Encoder 1 - NIC1
          - Haivision Encoder 2 - NIC1
          - Haivision Decoder 1 - NIC1
          - Haivision Decoder 2 - NIC1
        profile: HaivisionSRTTrafficBlue_site3    

# HaivisionSRTTrafficRed
  - name: HaivisionSRTTrafficRedPurple
    adapters:
      - switch_ports:
          - Ethernet12
          - Ethernet14
          - Ethernet16
          - Ethernet18
        switches: 
          - SW301-SITE3-P
          - SW301-SITE3-P
          - SW301-SITE3-P
          - SW301-SITE3-P
        descriptions:
          - Haivision Encoder 1 - NIC2
          - Haivision Encoder 2 - NIC2
          - Haivision Decoder 1 - NIC2
          - Haivision Decoder 2 - NIC2
        profile: HaivisionSRTTrafficRed_site3    

        
# PACIFIC INTERNET
  - name: PACIFIC INTERNET
    adapters:
      - switch_ports:
          - Ethernet33
        switches: 
          - SW301-SITE3-P
        descriptions:
          - PACIFIC INTERNET
        profile: ILD3_200mbps_prod_site3

