---
# test servers VMs.
# servers:
#   - name: SITE1-server1
#     adapters:
#       - endpoint_ports: [ Ethernet1]
#         switch_ports: [ Ethernet50]
#         switches: [ SW101-SITE1-B ]
#         profile: JXSVideoTrafficBlue_site1

#       - endpoint_ports: [ Ethernet2 ]
#         switch_ports: [ Ethernet50 ]
#         switches: [ SW102-SITE1-R ]
#         profile: JXSVideoTrafficRed_site1

#       - endpoint_ports: [ Ethernet3 ]
#         switch_ports: [ Ethernet50 ]
#         switches: [ SW103-SITE1-P ]
#         profile: HaivisionSRTTrafficBlue_site1

generic_devices:
##############################################
# Switchport config for SW101-SITE1-B

# JXSVideoTraffic
  - name: JXSVideoTrafficBlue
    # Definition of adapters on the server.
    adapters:
      - switch_ports:
          - Ethernet1
          - Ethernet2
          - Ethernet3
          - Ethernet9
          - Ethernet23
        switches: 
          - SW101-SITE1-B
          - SW101-SITE1-B
          - SW101-SITE1-B
          - SW101-SITE1-B
          - SW101-SITE1-B
        descriptions: 
          - Appear JPEG XS Kit 1 Sw 1 D1
          - Appear JPEG XS Kit 1 Sw 1 D2
          - SFP Populated for BU
          - TAG Multiviewer	NIC 1
          - Evertz 7890 MG	Trunk A
        profile: JXSVideoTrafficBlue_site1
    
# Haivision
  - name: HaivisionSRTTrafficBlue
    adapters:
      - switch_ports:
          - Ethernet11
          - Ethernet12
          - Ethernet13
          - Ethernet14
          - Ethernet15
        switches: 
          - SW101-SITE1-B
          - SW101-SITE1-B
          - SW101-SITE1-B
          - SW101-SITE1-B
          - SW101-SITE1-B
        descriptions: 
          - Haivison Gateway-NIC1
          - Haivison Encoder 101-NIC1
          - Haivison Encoder 102-NIC1
          - Haivison Decoder 11-NIC1
          - Haivison Decoder 12-NIC1
        profile: HaivisionSRTTrafficBlue_site1
# SITE5aki
  - name: SITE5akiBlue-Transit
    adapters:
      - switch_ports:
          - Ethernet19
        switches: 
          - SW101-SITE1-B
        descriptions: 
          - SITE5aki FW 100-Port9
        profile: SITE5AKI_TRANSIT
        enabled: false

  - name: SITE5akiBlue-Client
    adapters:
      - switch_ports:
          - Ethernet21
        switches: 
          - SW101-SITE1-B
        descriptions: 
          - SITE5aki FW 10-Port9 - Client
        profile: SITE5AKI_MX_TRUNK
        enabled: true

# Pseudowire
  - name: Pseudowire_25-Blue
    adapters:
      - switch_ports:
          - Ethernet25
        switches: 
          - SW101-SITE1-B
        descriptions: 
          - DATA PATH to SITE5 1
        profile: Pseudowire_Police_50

  - name: Pseudowire_26-Blue
    adapters:
      - switch_ports:
          - Ethernet26
        switches: 
          - SW101-SITE1-B
        descriptions: 
          - DATA PATH to SITE5 2
        profile: Pseudowire_Police_50

  - name: Pseudowire_27-Blue
    adapters:
      - switch_ports:
          - Ethernet27
        switches: 
          - SW101-SITE1-B
        descriptions: 
          - DATA PATH to SITE5 3
        profile: Pseudowire_Police_100

  - name: Pseudowire_28-Blue
    adapters:
      - switch_ports:
          - Ethernet28
        switches: 
          - SW101-SITE1-B
        descriptions: 
          - DATA PATH to SITE5 4
        profile: Pseudowire_Police_500

# WAN FROM SITE5 - BELL
  - name: WAN SITE5
    adapters:
      - switch_ports:
          - Ethernet41
          - Ethernet42
        switches: 
          - SW101-SITE1-B
          - SW101-SITE1-B
        descriptions: 
          - FW100-Port1
          - BU
        profile: WAN_SITE5_BELL

##############################################
# Switchport config for SW102-SITE1-R

# JXSVideoTraffic
  - name: JXSVideoTrafficRed
    # Definition of adapters on the server.
    adapters:
      - switch_ports:
          - Ethernet1
          - Ethernet2
          - Ethernet3
          - Ethernet9
          - Ethernet23
        switches: 
          - SW102-SITE1-R
          - SW102-SITE1-R
          - SW102-SITE1-R
          - SW102-SITE1-R
          - SW102-SITE1-R
        descriptions: 
          - Appear JPEG XS Kit 1 Sw 2 D1
          - Appear JPEG XS Kit 1 Sw 2 D2
          - SFP Populated for BU
          - TAG Multiviewer
          - Evertz 7890 MG	Trunk A
        profile: JXSVideoTrafficRed_site1
# Haivision
  - name: HaivisionSRTTrafficRed
    adapters:
      - switch_ports:
          - Ethernet11
          - Ethernet12
          - Ethernet13
          - Ethernet14
          - Ethernet15
        switches: 
          - SW102-SITE1-R
          - SW102-SITE1-R
          - SW102-SITE1-R
          - SW102-SITE1-R
          - SW102-SITE1-R
        descriptions: 
          - Haivison Gateway-NIC2
          - Haivison Encoder 101-NIC2
          - Haivison Encoder 102-NIC2
          - Haivison Decoder 11-NIC2
          - Haivison Decoder 12-NIC2
        profile: HaivisionSRTTrafficRed_site1

# SITE5aki
  - name: SITE5akiRed-Transit
    adapters:
      - switch_ports:
          - Ethernet19
        switches: 
          - SW102-SITE1-R
        descriptions: 
          - SITE5aki FW 100-Port10
        profile: SITE5AKI_TRANSIT
        enabled: true

  # - name: SITE5akiRed-Client
  #   adapters:
  #     - switch_ports:
  #         - Ethernet21
  #       switches: 
  #         - SW102-SITE1-R
  #       descriptions: 
  #         - SITE5aki FW 10-Port10 - Client
  #       profile: SITE5AKI_MX_TRUNK
  #       enabled: false


# Pseudowire Red
  - name: Pseudowire_25-Red
    adapters:
      - switch_ports:
          - Ethernet25
        switches: 
          - SW102-SITE1-R
        descriptions: 
          - DATA PATH to SITE5 5
        profile: Pseudowire_Police_50

  - name: Pseudowire_26-Red
    adapters:
      - switch_ports:
          - Ethernet26
        switches: 
          - SW102-SITE1-R
        descriptions: 
          - DATA PATH to SITE5 6
        profile: Pseudowire_Police_50

  - name: Pseudowire_27-Red
    adapters:
      - switch_ports:
          - Ethernet27
        switches: 
          - SW102-SITE1-R
        descriptions: 
          - DATA PATH to SITE5 7
        profile: Pseudowire_Police_100

  - name: Pseudowire_28-Red
    adapters:
      - switch_ports:
          - Ethernet28
        switches: 
          - SW102-SITE1-R
        descriptions: 
          - DATA PATH to SITE5 8
        profile: Pseudowire_Police_500

# WAN FROM SITE5 - ROGERS
  - name: WAN2 SITE5 ROGERS
    adapters:
      - switch_ports:
          - Ethernet41
          - Ethernet42
        switches: 
          - SW102-SITE1-R
          - SW102-SITE1-R
        descriptions: 
          - FW10-Port1
          - FW100-Port1
        profile: WAN_SITE5_ROGERS


##############################################
# Switchport config for SW103-SITE1-P

# Intercom
  - name: Intercom
    adapters:
      - switch_ports:
          - Ethernet1
          - Ethernet2
          - Ethernet3
        switches: 
          - SW103-SITE1-P
          - SW103-SITE1-P
          - SW103-SITE1-P
        description: RVON intercom 
        profile: Intercom_site1

# DataTransferEVS
  - name: DataTransferEVS
    adapters:
      - switch_ports:
          - Ethernet4
          - Ethernet5
        switches: 
          - SW103-SITE1-P
          - SW103-SITE1-P
        descriptions: 
          - EVS X File - Data Transfer - Standby
          - EVS X File - Data Transfer - NIC4
        profile: DataTransferEVS_site1          

# EdgeDeviceControl
  - name: EdgeDeviceControl
    adapters:
      - switch_ports:
          - Ethernet6
          - Ethernet7
          - Ethernet8
          - Ethernet9
          - Ethernet10
          - Ethernet11
          - Ethernet12
          - Ethernet31
          - Ethernet32
          - Ethernet33
          - Ethernet34
        switches: 
          - SW103-SITE1-P
          - SW103-SITE1-P
          - SW103-SITE1-P
          - SW103-SITE1-P
          - SW103-SITE1-P
          - SW103-SITE1-P
          - SW103-SITE1-P
          - SW103-SITE1-P
          - SW103-SITE1-P
          - SW103-SITE1-P
          - SW103-SITE1-P
        descriptions:
          - Stage Racer 2 Control - NIC 1
          - TAG MCM - NIC 3
          - Ops PC 1 - 
          - Ops PC 2 - 
          - Appear Control 1 - SW 1 CRTL
          - Appear Control 2 - SW 2 CRTL
          - TAG MCS - NIC 1
          - Ops Standby 1
          - Ops Standby 2
          - Dejero Waypoint
          - Evertz FR Controller
        profile: EdgeDeviceControl_site1
        # enabled: true 

# HaivisionSRTTrafficBlue
  - name: HaivisionSRTTrafficBluePurple
    adapters:
      - switch_ports:
          - Ethernet13
          - Ethernet15
          - Ethernet17
          - Ethernet19
          - Ethernet21
          - Ethernet23
          - Ethernet25
          - Ethernet27
          - Ethernet29
          - Ethernet35
          - Ethernet37
        switches: 
          - SW103-SITE1-P
          - SW103-SITE1-P
          - SW103-SITE1-P
          - SW103-SITE1-P
          - SW103-SITE1-P
          - SW103-SITE1-P
          - SW103-SITE1-P
          - SW103-SITE1-P
          - SW103-SITE1-P
          - SW103-SITE1-P
          - SW103-SITE1-P
        descriptions:
          - Haivision Decoder 11 - NIC1
          - Haivision Decoder 12 - NIC1
          - Haivision Decoder 13 - NIC1
          - Haivision Decoder 14 - NIC1
          - Haivision Decoder 15 - NIC1
          - Haivision Decoder 16 - NIC1
          - Haivision Decoder 17 - NIC1
          - Haivision Encoder 102 - NIC1
          - Haivision Encoder 103 - NIC1
          - Haivision Gateway - NIC1
          - Haivision Device - NIC1
        profile: HaivisionSRTTrafficBlue_site1    

# HaivisionSRTTrafficRed
  - name: HaivisionSRTTrafficRedPurple
    adapters:
      - switch_ports:
          - Ethernet14
          - Ethernet16
          - Ethernet18
          - Ethernet20
          - Ethernet22
          - Ethernet24
          - Ethernet26
          - Ethernet28
          - Ethernet30
          - Ethernet36
          - Ethernet38
        switches: 
          - SW103-SITE1-P
          - SW103-SITE1-P
          - SW103-SITE1-P
          - SW103-SITE1-P
          - SW103-SITE1-P
          - SW103-SITE1-P
          - SW103-SITE1-P
          - SW103-SITE1-P
          - SW103-SITE1-P
          - SW103-SITE1-P
          - SW103-SITE1-P
        descriptions:
          - Haivision Decoder 11 - NIC2
          - Haivision Decoder 12 - NIC2
          - Haivision Decoder 13 - NIC2
          - Haivision Decoder 14 - NIC2
          - Haivision Decoder 15 - NIC2
          - Haivision Decoder 16 - NIC2
          - Haivision Decoder 17 - NIC2
          - Haivision Encoder 102 - NIC2
          - Haivision Encoder 103 - NIC2
          - Haivision Gateway - NIC2
          - Haivision Device - NIC2
        profile: HaivisionSRTTrafficRed_site1    

        
# Prod Police
  - name: ProdiNet50mbps
    adapters:
      - switch_ports:
          - Ethernet39
          - Ethernet40
        switches: 
          - SW103-SITE1-P
          - SW103-SITE1-P
        descriptions:
          - Prod iNet 50Mbps - Drop 1
          - Prod iNet 50Mbps - Drop 2
        profile: Prod_Police_50mbps

  - name: ProdiNet100mbps
    adapters:
      - switch_ports:
          - Ethernet41
          - Ethernet42
          - Ethernet43
          - Ethernet44
          - Ethernet45
          - Ethernet46
        switches: 
          - SW103-SITE1-P
          - SW103-SITE1-P
          - SW103-SITE1-P
          - SW103-SITE1-P
          - SW103-SITE1-P
          - SW103-SITE1-P
        descriptions:
          - Prod iNet 100Mbps - Drop 1
          - Prod iNet 100Mbps - Drop 2
          - Prod iNet 100Mbps - Drop 3
          - Prod iNet 100Mbps - Drop 4
          - Prod iNet 100Mbps - Drop 5
          - Prod iNet 100Mbps - Drop 6
        profile: Prod_Police_100mbps

  - name: ProdiNet500mbps
    adapters:
      - switch_ports:
          - Ethernet47
        switches: 
          - SW103-SITE1-P
        descriptions:
          - Prod iNet 500Mbps - Drop 1
        profile: Prod_Police_500mbps

  - name: SITE5akiPurple-Client
    adapters:
      - switch_ports:
          - Ethernet48
        switches: 
          - SW103-SITE1-P
        descriptions: 
          - SITE5aki SW 11-Port48 - Client
        profile: SITE5AKI_MX_TRUNK
        enabled: true
