---
Production:
  - name: Production
    mac_vrf_vni_base: 10000
    mac_vrf_id_base: 10000
    vrfs:
      - name: Production
        vrf_id: 11111
        svis:
        # NetworkMgmt
          ## Internet Transit
          - id: 99
            tags:
              - "blue_site1"
              # - "red_site1"
            name: iTransit
            enabled: true
            ip_address: 10.1.99.5/28
            vxlan: false
            ip_virtual_router_addresses:
              - 10.1.99.4/28
          - id: 99
            tags:
              # - "blue_site1"
              - "red_site1"
            name: iTransit
            enabled: true
            vxlan: false
            ip_address: 10.1.99.6/28
            ip_virtual_router_addresses:
              - 10.1.99.4/28

          - id: 112
            tags:
              - "site1"
            name: NetworkMgmtSite1
            enabled: true
            ip_address: 10.1.12.1/24
            structured_config:
              dhcp_server_ipv4: true
          - id: 212
            tags:
              - "site2"
            name: NetworkMgmtSite2
            enabled: true
            ip_address: 10.2.12.1/24
            structured_config:
              dhcp_server_ipv4: true
            igmp_snooping_querier:
              enabled: true              
          - id: 312
            tags:
              - "site3"
            name: NetworkMgmtSite3
            enabled: true
            ip_address: 10.3.12.1/24
            structured_config:
              dhcp_server_ipv4: true
            igmp_snooping_querier:
              enabled: true              
          - id: 512
            tags:
              - "site5"
            name: NetworkMgmtSite5
            enabled: true
            ip_address: 10.5.12.1/24
        
        # EdgeDeviceControl
            structured_config:
              dhcp_server_ipv4: true
            igmp_snooping_querier:
              enabled: true              
          - id: 113
            tags:
              - "site1"
            name: EdgeDeviceControlSite1
            enabled: true
            ip_address: 10.1.13.1/24
            structured_config:
              dhcp_server_ipv4: true
          - id: 213
            tags:
              - "site2"
            name: EdgeDeviceControlSite2
            enabled: true
            ip_address: 10.2.13.1/24
            structured_config:
              dhcp_server_ipv4: true
            igmp_snooping_querier:
              enabled: true              
          - id: 313
            tags:
              - "site3"
            name: EdgeDeviceControlSite3
            enabled: true
            ip_address: 10.3.13.1/24
            structured_config:
              dhcp_server_ipv4: true
            igmp_snooping_querier:
              enabled: true              
          - id: 413
            tags:
              - "site4"
            name: EdgeDeviceControlSite4
            enabled: true
            ip_address: 10.4.13.1/24
            structured_config:
              dhcp_server_ipv4: true
            igmp_snooping_querier:
              enabled: true              
          - id: 513
            tags:
              - "site5"
            name: EdgeDeviceControlSite5
            enabled: true
            ip_address: 10.5.13.1/24
            structured_config:
              dhcp_server_ipv4: true
            igmp_snooping_querier:
              enabled: true              
        # Intercom
          - id: 120
            tags:
              - "purple_site1"
            name: IntercomSite1
            enabled: true
            ip_address: 10.1.20.1/24
            structured_config:
              dhcp_server_ipv4: true
          - id: 220
            tags:
              - "purple_site2"
            name: IntercomSite2
            enabled: true
            ip_address: 10.2.20.1/24
            structured_config:
              dhcp_server_ipv4: true
          - id: 320
            tags:
              - "site3"
            name: IntercomSite3
            enabled: true
            ip_address: 10.3.20.1/24
            structured_config:
              dhcp_server_ipv4: true
          - id: 520
            tags:
              - "site5"
            name: IntercomSite5
            enabled: true
            ip_address: 10.5.20.1/24
            structured_config:
              dhcp_server_ipv4: true
          # DataTransferEVS
          - id: 140
            tags:
              - "purple_site1"
            name: DataTransferEVSSite1
            enabled: true
            ip_address: 10.1.40.1/24
            structured_config:
              dhcp_server_ipv4: true
          - id: 240
            tags:
              - "purple_site2"
            name: DataTransferEVSSite2
            enabled: true
            ip_address: 10.2.40.1/24
            structured_config:
              dhcp_server_ipv4: true

          # Distribution 4 - 1000mbps Production
          - id: 184
            name: ILD4_1000mbps_prod_site1
            tags:
              - "purple_site1"
            enabled: true
            ip_address: 10.1.84.1/24
            structured_config:
              dhcp_server_ipv4: true
          - id: 284
            name: ILD4_1000mbps_prod_site2
            tags:
              - "purple_site2"
            enabled: true
            ip_address: 10.2.84.1/24
            structured_config:
              dhcp_server_ipv4: true
          - id: 384
            name: ILD4_1000mbps_prod_site3
            tags:
              - "site3"
            enabled: true
            ip_address: 10.3.84.1/24
            structured_config:
              dhcp_server_ipv4: true
          # BLUE    
          # HaivisionSRTTrafficBLUE
          # SITE1
          - id: 135
            tags:
              # - "blue_site1"
              - "purple_site1"
            name: HaivisionSRTTrafficBLUE
            enabled: true
            ip_address: 10.1.35.1/24
            structured_config:
              dhcp_server_ipv4: true
          # SITE2
          - id: 235
            tags:
              - "purple_site2"
            name: HaivisionSRTTrafficBLUE
            enabled: true
            ip_address: 10.2.35.1/24
            structured_config:
              dhcp_server_ipv4: true
          # SITE3
          - id: 335
            tags:
              - "purple_site3"
            name: HaivisionSRTTrafficBLUE
            enabled: true
            ip_address: 10.3.35.1/24
            structured_config:
              dhcp_server_ipv4: true
          # SITE5
          - id: 535
            tags:
              - "blue_site5"
            name: HaivisionSRTTrafficBLUE
            enabled: true
            ip_address: 10.5.35.1/24
            structured_config:
              dhcp_server_ipv4: true
          # HaivisionSRTTrafficRED
          - id: 136
            tags:
              # - "red_site1"
              - "purple_site1"
            name: HaivisionSRTTrafficRED
            enabled: true
            ip_address: 10.1.36.1/24
            structured_config:
              dhcp_server_ipv4: true
          # SITE2
          - id: 236
            tags:
              - "purple_site2"
            name: HaivisionSRTTrafficRED
            enabled: true
            ip_address: 10.2.36.1/24
            structured_config:
              dhcp_server_ipv4: true
          # SITE3
          - id: 336
            tags:
              - "purple_site3"
            name: HaivisionSRTTrafficRED
            enabled: true
            ip_address: 10.3.36.1/24
            structured_config:
              dhcp_server_ipv4: true
          # SITE5
          - id: 536
            tags:
              - "red_site5"
            name: HaivisionSRTTrafficRED
            enabled: true
            ip_address: 10.5.36.1/24
            igmp_snooping_querier:
              enabled: true
