---
WAN:
  - name: WAN
    mac_vrf_vni_base: 10000
    mac_vrf_id_base: 10000

    l2vlans:
      ## vxlan layer2
      - id: 5
        name: SITE5WANBell
        tags:
          - "blue_site1"
          - "blue_site4"
          - "blue_site5"
      - id: 6
        name: SITE5WANRogers
        tags:
          - "red_site1"
          - "red_site4"
          - "red_site5"
