---
- name: Build ACT / ContainerLab Topology
  hosts: "{{ target_hosts | default('FABRIC') }}"
  connection: local
  gather_facts: false
  vars:
    basename_act: "{{ lookup('env', 'PROJECT_NAME') | default('ce-act_' ~ lookup('community.general.random_string', length=10)) }}"
    # basename_act: "{{ lookup('env', 'PROJECT_NAME') }}"
    structured_folder: "{{ inventory_dir }}/intended/structured_configs/"
    output_folder: "{{ inventory_dir }}/act/"
    output_filename: "{{ basename_act }}.yml"
    avd_structured_config_file_format: yml
    # Whether to indicate to ACT to automatically configure CVP
    act_add_cvp: false
    act_cvp_auto_configuration: true
    # Versions
    act_eos_version: "4.33.1.1F"
    act_generic_os_version: "ubuntu-2404-lts-amd64"
    act_tools_os_version: "ubuntu-pro-2204-lts"
    act_cvp_version: "2024.3.2"
    # Device (veos/generic) user/pass
    # act_cvp_user: "root"
    act_cvp_password: "cvproot"
    act_add_connected_nodes: true
    act_connected_nodes_map:
      server: 'generic'
      workstation: 'generic'
    # act_veos_internet_access: true
    act_use_device_models: false

    # ContainerLab Config
    clab_name: "{{ basename_act }}"
    # clab_prefix: ""
    # clab_output_folder: "{{ inventory_dir }}/clab"
    clab_output_filename: "{{ basename_act }}.clab.yml"
    clab_eos_version: "arista/ceos:4.34.1F"
    # clab_linux_image: "ghcr.io/aristanetworks/aclabs/host-ubuntu:rev1.0"
    # clab_add_tools_server: true
    clab_tools_server_ip: 172.20.20.200
    clab_avd_configs: "{{ inventory_dir }}/clab/intended/configs"
    # true = default config or false = AVD config
    clab_device_default: false
    clab_static_mgmt_ip: false
    clab_connected_nodes_map:
      server: 'linux'
      workstation: 'linux'
    global_vars_on: "{{ lookup('env', 'GLOBAL_VARS_ON')  | default('False') | bool }}"
    env_lookup_result: "{{ lookup('env', 'GLOBAL_VARS_FILE') }}"

    global_vars_file: >-
      {{ (inventory_dir ~ '/../../' ~ env_lookup_result) if env_lookup_result
          else (playbook_dir ~ '/../global_vars/global_dc_vars.yml') }}

  tasks:
    - name: Print the test variable from global_vars
      ansible.builtin.debug:
        msg: "GB_VAR: {{ global_vars_on }} -  {{ env_lookup_result }}"

    - name: Import Global Vars
      ansible.builtin.include_vars: "{{ item }}"
      with_items:
        - "{{ global_vars_file }}"
      when: global_vars_on

    # - name: Import Global Vars
    #   ansible.builtin.include_vars: "{{ item }}"
    #   with_items:
    #     - "../global_vars/global_dc_vars.yml"

    - name: Generate ACT / ConatinerLabs Topology File
      vars:
        act_device_user: "{{ ansible_user }}"
        act_device_password: "{{ ansible_password }}"

      ansible.builtin.import_role:
        # For testing act-topgen
        # name: act_topgen/act-topgen
        name: act-topgen
