- name: Configuration deployment with CVP
  hosts: "{{ target_hosts | default('FABRIC') }}"
  connection: local
  gather_facts: false
  tasks:
    # - name: Import Global Vars
    #   ansible.builtin.include_vars: "{{ item }}"
    #   with_items:
    #     - "../global_vars/global_dc_vars.yml"

    - name: Deploy configurations and tags to CloudVision
      ansible.builtin.import_role:
        name: arista.avd.cv_deploy
      vars:
        cv_server: "{{ lookup('env', 'CVAAS_SERVER') }}"
        # cv_server: www.cv-prod-na-northeast1-b.arista.io
        cv_token: "{{ lookup('env', 'CVAAS_TOKEN') }}"
        container_root: "{{ target_hosts | default('FABRIC') }}"
        # Workspace state
        cv_submit_workspace: false

        # Change Control state
        cv_run_change_control: false

        # Set the template to be used to generate the configlet names in CloudVision Static Config Studio.
        cv_configlet_name_template: "AVD-${hostname}"
        cv_verify_certs: false
